displayName: Replace Path Regex
type: middleware

import: github.com/patternMiner/replacepathregex

summary: '[Replace Path Regex] Customize path regex'

testData:
  regex: "^([^/]+)/admin/(.*)$"
  replacement: "/$2"
